### ISSUE TITLE
Wrong type of argument

### ISSUE THREAD

**Issue by truls** [petergardfjall/emacs-immaterial-theme#1]
https://github.com/petergardfjall/emacs-immaterial-theme/blob/225b6d41f547146d511c0ba47f62069ad1e0c9cd/immaterial-theme.el#L376

After updating to a version including the above line I'm getting a wrong type of argument error complaining about the type of the argument of the :background attribute when treemacs is initializing. Should "red" be a string?

**Comment by petergardfjall** [comment]
Ah crap. That made it's way in by mistake. Should be fixed now: 660f999
Thanks for reporting!

**Comment by truls** [comment]
Awesome! Thanks a lot. Thanks for your work on the theme. I'm really enjoying it
